### ISSUE TITLE
Upload to MEDIA tab "Uploaded Virtual Disks" section from Truenas

### ISSUE THREAD

**Issue by stondino00** [9072997/scale-backup#2]
Is there a way to use this program or another means to upload an exported virtual disk to the MEDIA section in options and the Uploaded Virtual Disks area?  We are trying to do that from Truenas to attach the disk to a VM instead of restoring back to a new or existing vm.

**Comment by 9072997** [comment]
Right now there is not a way built in to the program to restore a disk to an existing VM, but you can do it by using the API directly with curl:

fill in your scale username and password, the IP for any one of your nodes, the filename, and the length of the file in bytes:
```
curl -k 'https://admin:your%20password@10.1.2.3/rest/v1/VirtualDisk/upload?filename=example.qcow2&filesize=196688' --upload-file example.qcow2
```

**Comment by 9072997** [comment]
This is now supported via the [`upload-disk-media`](https://github.com/9072997/scale-backup#upload-disk-media) command
