### ISSUE TITLE
Should I be able to backup all VMs if there's no "Tag" in the schedule part of config?

### ISSUE THREAD

**Issue by MisterC925** [9072997/scale-backup#3]
I have a pretty small Scale install and want to back up every VM weekly.

When I remove "Tag = " or set it to "Tag = ''" the scheduled backups refuse to run.

I get:
No backups started because the schedule is not configured

The docs seem to indicate the Tag is optional?  Am I mistaken or just doing it wrong?

Thanks!

**Comment by 9072997** [comment]
I'm not at my desk right now, so I'm just looking through the code on my phone, but that does look like a bug. I'll try to have a fix for it by the end of the week. Alternately, you could add a tag to all of your VMs, and specify that in the config (but you probably already knew that)

**Comment by 9072997** [comment]
I think I have this fixed in 06813e2 (released as v1.1.1). Do you mind to check if it fixes your issue?

**Comment by MisterC925** [comment]
That worked perfectly, thank you
